[package]
name = "example-barebone"
version = "0.1.0"
edition = "2021"

[dependencies]
rustpython-vm = { path = "../../vm", default-features = false }

[workspace]

[patch.crates-io]
radium = { version = "1.1.0", git = "https://github.com/youknowone/ferrilab", branch = "fix-nightly" }
